name: Python application

on:
  pull_request

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install
      run: |
        python -m pip install --upgrade pip
        pip install flake8 black
    - name: Lint
      run: |
        black --check --line-length 80 .
        flake8 --ignore=E501,W503,E203 .
